/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.dialog;

import java.awt.Color;
import entity.pembelian;
import entity.supplier;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.EventObject;
import javax.swing.DefaultCellEditor;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import main.main;
import panel.Laporan;
import repository.pembelianRepository;
import repository.supplierRepository;
import repository.userRepository;
import util.Conn;

/**
 *
 * @author Be Mine
 */
public class editLaporanPembelian extends Dialog {
    userRepository pegawai = new userRepository();
    supplierRepository supp = new supplierRepository();
    pembelianRepository beli =new pembelianRepository();
    private int id ;
    private int idd = Laporan.id;
    int iddsupplier = beli.get(idd).getSupplier().getId();
    String iddsupplier1 = beli.get(idd).getSupplier().getNama_supplier();
    
    public editLaporanPembelian(JFrame frame) {
        super(frame);
        initComponents();
        DefaultCellEditor cellEditor = new DefaultCellEditor(new JTextField()) {
    @Override
    public boolean isCellEditable(EventObject e) {
        return false;
    }
};
        table.setDefaultEditor(Object.class, cellEditor);
        load_tabelsup();
        jPanel2.setVisible(false);
        txt_supplier.setText(iddsupplier1);
        txt_jumlahbayar.setText(String.valueOf(beli.get(idd).getBayartunai()));
        txt_totalharga.setText(String.valueOf(beli.get(idd).getTotal_harga()));
        txt_kembalian.setText(String.valueOf(beli.get(idd).getKembalian()));
    }
    public void load_tabelsup() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("NAMA_OBAT");
        model.addColumn("NO TELP");
        model.addColumn("ALAMAT");

        try {
            for (supplier apa : supp.get()) {
                model.addRow(new Object[]{
                    apa.getId(),
                    apa.getNama_supplier(),
                    apa.getNo_tlp(),
                    apa.getAlamat()

                });
            }
            table.setModel(model);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public void load_tabelsup(String search) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("NAMA_SUPPLIER");
        model.addColumn("NO_TELP");
        model.addColumn("ALAMAT");

        try {
            String sql = "SELECT * FROM supplier WHERE id LIKE ? OR nama_supplier LIKE ?";
            Connection koneksi = (Connection) Conn.configDB();
            PreparedStatement pst = koneksi.prepareStatement(sql);
            pst.setString(1, "%" + search + "%");
            pst.setString(2, "%" + search + "%");

            ResultSet res = pst.executeQuery();

            while (res.next()) {
                model.addRow(new Object[]{
                    res.getString("id"),
                    res.getString("nama_supplier"),
                    res.getString("no_tlp"),
                    res.getString("alamat")
                });
            }

            table.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        btnedit = new javax.swing.JLabel();
        btnbatal = new javax.swing.JLabel();
        txt_kembalian = new javax.swing.JTextField();
        txt_jumlahbayar = new javax.swing.JTextField();
        txt_totalharga = new javax.swing.JTextField();
        txt_supplier = new javax.swing.JTextField();
        btncarisuplier = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new view.swing.Table();
        bg1 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new Color(0,0,0,0)
        );
        jPanel1.setLayout(null);

        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnedit1.png"))); // NOI18N
        btnedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btneditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btneditMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btneditMousePressed(evt);
            }
        });
        jPanel1.add(btnedit);
        btnedit.setBounds(310, 540, 190, 60);

        btnbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnbatal1.png"))); // NOI18N
        btnbatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbatalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbatalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbatalMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnbatalMousePressed(evt);
            }
        });
        jPanel1.add(btnbatal);
        btnbatal.setBounds(100, 540, 190, 60);

        txt_kembalian.setBorder(null);
        txt_kembalian.setFocusable(false);
        txt_kembalian.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(txt_kembalian);
        txt_kembalian.setBounds(50, 463, 520, 40);

        txt_jumlahbayar.setBorder(null);
        txt_jumlahbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jumlahbayarActionPerformed(evt);
            }
        });
        txt_jumlahbayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_jumlahbayarKeyReleased(evt);
            }
        });
        jPanel1.add(txt_jumlahbayar);
        txt_jumlahbayar.setBounds(50, 373, 520, 40);

        txt_totalharga.setBorder(null);
        txt_totalharga.setFocusable(false);
        txt_totalharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalhargaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_totalharga);
        txt_totalharga.setBounds(50, 283, 520, 40);

        txt_supplier.setBorder(null);
        txt_supplier.setFocusable(false);
        jPanel1.add(txt_supplier);
        txt_supplier.setBounds(50, 193, 390, 40);

        btncarisuplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btncarisupplier1.png"))); // NOI18N
        btncarisuplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncarisuplierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncarisuplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncarisuplierMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btncarisuplierMousePressed(evt);
            }
        });
        jPanel1.add(btncarisuplier);
        btncarisuplier.setBounds(450, 190, 140, 40);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebg/formeditlaporan pembelian.png"))); // NOI18N
        jPanel1.add(bg);
        bg.setBounds(0, -30, 620, 720);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(100, 0, 620, 640);

        jPanel2.setBackground(new Color(0,0,0,0)
        );
        jPanel2.setLayout(null);

        jScrollPane1.setBorder(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(50, 200, 700, 260);

        bg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebg/pilihsuppilerkosong.png"))); // NOI18N
        jPanel2.add(bg1);
        bg1.setBounds(0, 100, 802, 420);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 10, 800, 640);

        setSize(new java.awt.Dimension(819, 654));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btneditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMouseClicked
        supplier sas = new supplier(supp.get(id).getId());
        System.out.println(sas);
        pembelian gas = new pembelian(idd,sas, Integer.valueOf(txt_totalharga.getText()),
                 Integer.valueOf(txt_jumlahbayar.getText()),
                 Integer.valueOf(txt_kembalian.getText()));
        boolean cobak = beli.update(gas);
        if(cobak){
            
            System.out.println("berhasil");
            closeMessage();
        }else{
            System.out.println("gagal");
        }
    }//GEN-LAST:event_btneditMouseClicked

    private void btnbatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbatalMouseClicked
    
        closeMessage();
    }//GEN-LAST:event_btnbatalMouseClicked

    private void btnbatalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbatalMouseEntered
        btnbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnbatal2.png")));
    }//GEN-LAST:event_btnbatalMouseEntered

    private void btnbatalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbatalMouseExited
        btnbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnbatal1.png")));
    }//GEN-LAST:event_btnbatalMouseExited

    private void btnbatalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbatalMousePressed
        btnbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnbatal3.png")));
    }//GEN-LAST:event_btnbatalMousePressed

    private void btneditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMouseEntered
        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnedit2.png")));
    }//GEN-LAST:event_btneditMouseEntered

    private void btneditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMouseExited
        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnedit1.png")));
    }//GEN-LAST:event_btneditMouseExited

    private void btneditMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMousePressed
        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnedit3.png")));
    }//GEN-LAST:event_btneditMousePressed

    private void txt_jumlahbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jumlahbayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jumlahbayarActionPerformed

    private void txt_totalhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalhargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalhargaActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
    int baris = table.rowAtPoint(evt.getPoint());
        String idd = table.getValueAt(baris, 0).toString();
        id = Integer.valueOf(idd);
        System.out.println(id);
        txt_supplier.setText(supp.get(id).getNama_supplier());
        jPanel2.setVisible(false);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_tableMouseClicked

    private void txt_jumlahbayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jumlahbayarKeyReleased
    txt_kembalian.setText(String.valueOf(Integer.valueOf(txt_jumlahbayar.getText()) - Integer.valueOf(txt_totalharga.getText())));
    }//GEN-LAST:event_txt_jumlahbayarKeyReleased

    private void btncarisuplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncarisuplierMouseClicked
        jPanel2.setVisible(true);
        jPanel1.setVisible(false);
    }//GEN-LAST:event_btncarisuplierMouseClicked

    private void btncarisuplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncarisuplierMouseEntered
        btncarisuplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btncarisupplier2.png")));
    }//GEN-LAST:event_btncarisuplierMouseEntered

    private void btncarisuplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncarisuplierMouseExited
        btncarisuplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btncarisupplier1.png")));
    }//GEN-LAST:event_btncarisuplierMouseExited

    private void btncarisuplierMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncarisuplierMousePressed
        btncarisuplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btncarisupplier3.png")));
    }//GEN-LAST:event_btncarisuplierMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bg1;
    private javax.swing.JLabel btnbatal;
    private javax.swing.JLabel btncarisuplier;
    private javax.swing.JLabel btnedit;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private view.swing.Table table;
    private javax.swing.JTextField txt_jumlahbayar;
    private javax.swing.JTextField txt_kembalian;
    private javax.swing.JTextField txt_supplier;
    private javax.swing.JTextField txt_totalharga;
    // End of variables declaration//GEN-END:variables
}
