/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

/**
 *
 * @author semafie
 */
public class login_lupapassword extends javax.swing.JPanel {

    /**
     * Creates new form login_lupapassword
     */
    public login_lupapassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btneye1 = new javax.swing.JLabel();
        btneye = new javax.swing.JLabel();
        btn_gantipassword = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setLayout(null);

        btneye1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/eye1.png"))); // NOI18N
        add(btneye1);
        btneye1.setBounds(930, 247, 50, 30);

        btneye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/eye1.png"))); // NOI18N
        add(btneye);
        btneye.setBounds(930, 325, 50, 30);

        btn_gantipassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnubahpassword1.png"))); // NOI18N
        add(btn_gantipassword);
        btn_gantipassword.setBounds(620, 460, 310, 75);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebg/bg gantipassword.png"))); // NOI18N
        add(bg);
        bg.setBounds(0, 0, 1044, 590);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btn_gantipassword;
    private javax.swing.JLabel btneye;
    private javax.swing.JLabel btneye1;
    // End of variables declaration//GEN-END:variables
}
